### ISSUE TITLE
Safari: sometimes code block can't scroll

### ISSUE THREAD

**Issue by cntrump** [josephhutch/aether#17]
test page [here](https://boringdocker.com/post/2019-01-28_docker-nginx/), tested macOS 10.14.3/Safari and macOS 10.14.2/Safari
sometimes refresh page is OK, I check the css and found that:

![](https://github.com/cntrump/pics/raw/master/aether/cannotscroll.png)

![](https://github.com/cntrump/pics/raw/master/aether/bottom.png)

**Comment by cntrump** [comment]
Path ?
```css
pre {
    padding-top: 16px;
    padding-bottom: 16px
}
```
